Repository npm/.github, pull requests merged in 2020-07, with the labels that each got.

#27 fix: update settings.yml to stop dropping admin privileges
  .github/settings.yml
Labels: bug

#19 fix(workflows): remove github actions default workflow git setup
  .github/workflows/default.yml
Labels: bug

#28 fix: drop the enforce_admins setting so admins can override merges
  .github/settings.yml
Labels: bug

#31 chore: Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#32 feat: deploy workflow template
  README.md
  icons/npm-deploy.svg
  workflow-templates/deploy.properties.json
  workflow-templates/deploy.yaml
Labels: feature
